docs: updated the faq.md file
bandada-infra/bandada pull request #542
Opened 2024-07-31 23:06 UTC by od-hunter

added difference between the Bandada and Semaphore  in the faq.md file

2024-08-05 20:47 UTC, vplasencia commented
Hey @od-hunter! Thank you very much for the PR. I will review it this week.

2024-08-11 11:58 UTC, vplasencia approved these changes
Hey @od-hunter! Thank you for this PR. I left some comments.

I think these resources can help to understand more about the differences between Semaphore and Bandada:

- https://github.com/bandada-infra/bandada/issues/438#issuecomment-2258579348 

- [Semaphore docs](https://docs.semaphore.pse.dev/)

- [Semaphore resources](https://docs.semaphore.pse.dev/resources)

- [Bandada resources](https://docs.bandada.pse.dev/resources)

- [Bandada docs](https://docs.bandada.pse.dev/)

This FAQ does not need to be a long section, it can be short but direct to the point. Also, please, let me know if you need any help.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +When it comes to [Bandada](https://bandada.pse.dev/) and [Semaphore](https://semaphore.pse.dev/), you might find yourself wondering how these two platforms stack up against each other. Both are desig
Semaphore is not a platform, it's a project or protocol.

Neither project is focused on project management or automation.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +- **Customization Enthusiasts:** Who need a platform that can be tailored to their specific workflow requirements.
This is not very accurate. Bandada is for DAOs, developers, teams and organizations that would like to manage and work with privacy preserving groups.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +- **High-Volume Applications:** Where performance and scalability are key considerations.
This is not accurate. Semaphore is mainly for developers who need to build a project related to identities, anonymous group membership proofs and anonymous interactions.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +| **Target Users**            | Teams, organizations, collaborative environments         | Developers, DevOps teams, software projects       |
This comparison might not be entirely correct. 

If we add a table, we could compare both projects following some main features like off-chain group management, identity creation, etc.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +- **Choose Semaphore** if your primary goal is to streamline and automate your development and deployment processes, especially in high-volume environments.
This is not entirely accurate. You can think about the main features of each of them to know when to choose one or the other.

2024-08-11 11:58 UTC, vplasencia commented on apps/docs/docs/faq.md
> +- **Scalability:** Handles large-scale projects and high traffic efficiently.
This section is not entirely correct. More info about key features of Semaphore: https://docs.semaphore.pse.dev/#features

2024-08-11 12:00 UTC, vplasencia requested changes
Hey @od-hunter! Thank you for this PR. I left some comments.

I think these resources can help to understand more about the differences between Semaphore and Bandada:

- https://github.com/bandada-infra/bandada/issues/438#issuecomment-2258579348 

- [Semaphore docs](https://docs.semaphore.pse.dev/)

- [Semaphore resources](https://docs.semaphore.pse.dev/resources)

- [Bandada resources](https://docs.bandada.pse.dev/resources)

- [Bandada docs](https://docs.bandada.pse.dev/)

This FAQ does not need to be a long section, it can be short but direct to the point. Also, please, let me know if you need any help.

2024-08-11 14:58 UTC, od-hunter commented
@vplasencia , so sorry will send a more accurate pr

2024-08-12 08:14 UTC, vplasencia commented
Hey @od-hunter no worries. Thank you very much and let me know if you need help.

2024-09-02 16:02 UTC, samajammin commented
Hey folks - any progress on this?

@vplasencia perhaps worth just merging this then making the updates you see fit?

2024-09-09 15:59 UTC, vplasencia commented
Hey @od-hunter! This is a high priority task now, so I will work on it to finish it asap. 

Then I will need to close your PR, sorry about it, but feel free to ask for any other `good first issue` here: https://github.com/bandada-infra/bandada/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Thank you! 🙏

I added the same comment in the issue: https://github.com/bandada-infra/bandada/issues/438#issuecomment-2338492944

2024-09-09 15:59 UTC, closed without merging