feat(component): implemented a copy link button for copying invited c…
bandada-infra/bandada pull request #645
Opened 2024-12-17 19:48 UTC by pheobeayo

…odes

## Description
implemented invited code links in button

implemented invited code links in button
## Related Issue
Issue #635

https://github.com/bandada-infra/bandada/issues/635#issuecomment-2541856362
## Does this introduce a breaking change?

-   [ ] Yes
-   [ No] No

## Other information

2024-12-27 15:07 UTC, vplasencia requested changes
Hey @pheobeayo! Thank you very much for this PR.

It looks great, but it would be nice to move the new invite code box to the modal that opens after clicking the `Add member` button. The issue description can help but feel free to ask any questions you may have.

2025-01-08 11:48 UTC, pheobeayo commented
> Hey @pheobeayo! Thank you very much for this PR.
> 
> It looks great, but it would be nice to move the new invite code box to the modal that opens after clicking the `Add member` button. The issue description can help but feel free to ask any questions you may have.

Kindly review the changes made please

2025-01-08 11:57 UTC, vplasencia commented
Hey @pheobeayo! I will review the PR as soon as possible. Thank you!

2025-01-10 00:29 UTC, vplasencia commented
Hey @pheobeayo! Could you update your branch with the latest changes of the main branch and fix the branch conflict? Please, let me know if you need any help to do it.

2025-01-13 19:59 UTC, vplasencia requested changes
Hey @pheobeayo! Thank you very much for the updates.

The idea of this implementation is correct but this feature should be implemented inside the [`add-member-modal.tsx`](https://github.com/bandada-infra/bandada/blob/main/apps/dashboard/src/components/add-member-modal.tsx) file. 

The new additions would be something like:

```ts
    const {
        hasCopied: hasCopiedInviteCode,
        value: inviteCode,
        setValue: setInviteCode,
        onCopy: onCopyInviteCode
    } = useClipboard("")
    
    -------------------------------------
    
        const generateInviteLink = useCallback(async () => {
        const inviteLink = await bandadaAPI.generateMagicLink(group.id)

        if (inviteLink === null) {
            return
        }

        setClientLink(inviteLink)
        const index = inviteLink.lastIndexOf("=")
        const inviteCodeLink = inviteLink.substring(index + 1)
        setInviteCode(inviteCodeLink)
    }, [group, setClientLink, setInviteCode])
    
    -------------------------------------
    
                                {!group.credentials && (
                                <>
                                    <Text mb="10px" color="balticSea.800">
                                        Share invite code
                                    </Text>

                                    <InputGroup size="lg">
                                        <Input
                                            pr="50px"
                                            placeholder="Invite code"
                                            value={inviteCode}
                                            isDisabled
                                        />
                                        <InputRightElement mr="5px">
                                            <Tooltip
                                                label={
                                                    hasCopiedInviteCode
                                                        ? "Copied!"
                                                        : "Copy"
                                                }
                                                closeOnClick={false}
                                                hasArrow
                                            >
                                                <IconButton
                                                    variant="link"
                                                    aria-label="Copy invite link"
                                                    onClick={onCopyInviteCode}
                                                    onMouseDown={(e) =>
                                                        e.preventDefault()
                                                    }
                                                    icon={
                                                        <Icon
                                                            color="sunsetOrange.600"
                                                            boxSize="5"
                                                            as={FiCopy}
                                                        />
                                                    }
                                                />
                                            </Tooltip>
                                        </InputRightElement>
                                    </InputGroup>
                                </>
                            )}
```

The final file would be something like:

```ts
import { getSemaphoreContract } from "@bandada/utils"
import {
    AbsoluteCenter,
    Box,
    Button,
    Divider,
    Heading,
    Icon,
    IconButton,
    Input,
    InputGroup,
    InputRightElement,
    Modal,
    ModalBody,
    ModalContent,
    ModalOverlay,
    Text,
    Textarea,
    Tooltip,
    useClipboard
} from "@chakra-ui/react"
import { useCallback, useEffect, useState } from "react"
import { FiCopy } from "react-icons/fi"
import { useSigner } from "wagmi"
import * as bandadaAPI from "../api/bandadaAPI"
import { Group } from "../types"
import parseMemberIds from "../utils/parseMemberIds"

export type AddMemberModalProps = {
    isOpen: boolean
    onClose: (value?: string[]) => void
    group: Group
}

export default function AddMemberModal({
    isOpen,
    onClose,
    group
}: AddMemberModalProps): JSX.Element {
    const [_memberIds, setMemberIds] = useState<string>("")
    const [_isLoading, setIsLoading] = useState(false)
    const {
        hasCopied,
        value: _clientLink,
        setValue: setClientLink,
        onCopy
    } = useClipboard("")
    const {
        hasCopied: hasCopiedInviteCode,
        value: inviteCode,
        setValue: setInviteCode,
        onCopy: onCopyInviteCode
    } = useClipboard("")
    const { data: signer } = useSigner()

    useEffect(() => {
        setMemberIds("")

        if (group.credentials) {
            setClientLink(
                `${import.meta.env.VITE_CLIENT_URL}?credentialGroupId=${
                    group.id
                }`
            )
        }
    }, [group, setClientLink])

    const addMember = useCallback(async () => {
        const memberIds = parseMemberIds(_memberIds)
        if (memberIds.length === 0) {
            alert("Please enter at least one member id!")
            return
        }

        const uniqueMemberIds = new Set(memberIds)
        if (uniqueMemberIds.size !== memberIds.length) {
            alert("Please ensure there are no repeated member IDs!")
            return
        }
        if (group.type === "on-chain" && group.members) {
            const existingMembers = new Set(
                group.members.map((memberId) => BigInt(memberId))
            )

            const conflictingMembers = []

            for (const memberId of memberIds) {
                const parsedMemberId = BigInt(memberId)

                if (existingMembers.has(parsedMemberId)) {
                    conflictingMembers.push(parsedMemberId)
                }
            }

            if (conflictingMembers.length > 0) {
                if (conflictingMembers.length === 1) {
                    alert(
                        `Member ID ${conflictingMembers[0]} already exists in the group.`
                    )
                } else {
                    alert(
                        `Member IDs ${conflictingMembers.join(
                            ", "
                        )} already exist in the group.`
                    )
                }
                return
            }
        }

        const confirmMessage = `
Are you sure you want to add the following members?
${memberIds.join("\n")}
        `

        if (!window.confirm(confirmMessage)) {
            return
        }

        setIsLoading(true)

        if (group.type === "off-chain") {
            if ((await bandadaAPI.addMembers(group.id, memberIds)) === null) {
                setIsLoading(false)
                return
            }

            setIsLoading(false)
            onClose(memberIds)
        } else {
            if (!signer) {
                alert("No valid signer for your transaction!")

                setIsLoading(false)
                return
            }

            try {
                const semaphore = getSemaphoreContract("sepolia", signer as any)

                await semaphore.addMembers(group.id, memberIds)

                setIsLoading(false)
                onClose(memberIds)
            } catch (error) {
                alert(
                    "Some error occurred! Check if you're on Sepolia network and the transaction is signed and completed"
                )

                setIsLoading(false)
            }
        }
    }, [onClose, _memberIds, group, signer])

    const generateInviteLink = useCallback(async () => {
        const inviteLink = await bandadaAPI.generateMagicLink(group.id)

        if (inviteLink === null) {
   [...]

2025-01-14 08:21 UTC, pheobeayo commented
@vplasencia , thank you!, I will work on the update.

2025-01-16 10:30 UTC, pheobeayo commented
Hey @vplasencia , How do I fix the test code issues, I have implemented the invite code link in the appropriate place as requested, however where debugging the test codes, I didn't see the issue from my PR but how can this be fixed? any help you can render regarding this?

2025-01-16 23:43 UTC, vplasencia commented
Hey @pheobeayo the CI issue is gone now. I just had to re-run the tests in the CI.

2025-01-17 08:46 UTC, pheobeayo commented
> Hey @pheobeayo the CI issue is gone now. I just had to re-run the tests in the CI.

Thank you so much @vplasencia , Please can you kindly review this.

2025-01-17 15:22 UTC, vplasencia requested changes
Hey @pheobeayo! Thank you very much for the update. I just left one comment. When it's solved, the PR will be ready to be merged.

2025-01-17 15:22 UTC, vplasencia commented on apps/dashboard/src/pages/group.tsx
> -                    (
Could you please add this parenthesis back, since it's not necessary to remove it?

2025-01-17 16:13 UTC, pheobeayo commented on apps/dashboard/src/pages/group.tsx
> -                    (
Okay fixed!

2025-01-18 08:19 UTC, pheobeayo commented
> Hey @pheobeayo! Thank you very much for the update. I just left one comment. When it's solved, the PR will be ready to be merged.

I have fixed this. Kindly review this, @vplasencia. Once this is successfully merged, I would like to solve the other issue I was assigned to.

2025-01-18 11:24 UTC, vplasencia approved these changes
Looks great! Thank you very much @pheobeayo!

2025-01-18 11:25 UTC, merged